# Generated by Django 4.0.1 on 2022-04-08 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.UUIDField(default=uuid.uuid4)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('slug', models.SlugField()),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Awating Divorce', 'Awaiting Divorce')], max_length=20)),
                ('DOB', models.DateField()),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('buddhist', 'Buddhist'), ('sikh', 'Sikh'), ('jain', 'Jain'), ('jewish', 'Jewish'), ('other', 'Other'), ('no Religion', 'No Religion')], max_length=15)),
                ('location', models.CharField(choices=[('achham', 'Achham'), ('arghakhanchi', 'Arghakhanchi'), ('baglung', 'Baglung'), ('baitadi', 'Baitadi'), ('bajhang', 'Bajhang'), ('bajura', 'Bajura'), ('banke', 'Banke'), ('bara', 'Bara'), ('bardiya', 'Bardiya'), ('bhaktapur', 'Bhaktapur'), ('bhojpur', 'Bhojpur'), ('chitwan', 'Chitwan'), ('dadeldhura', 'Dadeldhura'), ('dailekh', 'Dailekh'), ('dang', 'Dang'), ('darchula', 'Darchula'), ('dhading', 'Dhading'), ('dhankuta', 'Dhankuta'), ('dhanusa', 'Dhanusa'), ('dolakha', 'Dolakha'), ('dolpa', 'Dolpa'), ('doti', 'Doti'), ('gorkha', 'Gorkha'), ('gulmi', 'Gulmi'), ('humla', 'Humla'), ('ilam', 'Ilam'), ('jajarkot', 'Jajarkot'), ('jhapa', 'Jhapa'), ('jumla', 'Jumla'), ('kailali', 'Kailali'), ('kalikot', 'Kalikot'), ('kanchanpur', 'Kanchanpur'), ('kapilvastu', 'Kapilvastu'), ('kaski', 'Kaski'), ('kathmandu', 'Kathmandu'), ('kavrepalanchok', 'Kavrepalanchok'), ('khotang', 'Khotang'), ('lalitpur', 'Lalitpur'), ('lamjung', 'Lamjung'), ('mahottari', 'Mahottari'), ('makawanpur', 'Makawanpur'), ('manang', 'Manang'), ('morang', 'Morang'), ('mugu', 'Mugu'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('nawalpur', 'Nawalpur'), ('nuwakot', 'Nuwakot'), ('okhaldhunga', 'Okhaldhunga'), ('palpa', 'Palpa'), ('panchthar', 'Panchthar'), ('parasi', 'Parasi'), ('parbat', 'Parbat'), ('parsa', 'Parsa'), ('pyuthan', 'Pyuthan'), ('ramechhap', 'Ramechhap'), ('rasuwa', 'Rasuwa'), ('rautahat', 'Rautahat'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('rukum paschim', 'Rukum Paschim'), ('rupandehi', 'Rupandehi'), ('salyan', 'Salyan'), ('sankhuwasabha', 'Sankhuwasabha'), ('saptari', 'Saptari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('sindhupalchok', 'Sindhupalchok'), ('siraha', 'Siraha'), ('solukhumbu', 'Solukhumbu'), ('sunsari', 'Sunsari'), ('surkhet', 'Surkhet'), ('syangja', 'Syangja'), ('tanahu', 'Tanahu'), ('taplejung', 'Taplejung'), ('terhathum', 'Terhathum'), ('udayapur', 'Udayapur')], max_length=20)),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=10)),
                ('Rashi', models.CharField(choices=[('mesh', 'Mesh'), ('bris', 'Bris'), ('mithun', 'Mithun'), ('karkat', 'Karkat'), ('singha', 'Singha'), ('kanya', 'Kanya'), ('tula', 'Tula'), ('brischik', 'Brischik'), ('dhanu', 'Dhanu'), ('makar', 'Makar'), ('kumba', 'Kumba'), ('min', 'Min')], max_length=10)),
                ('education', models.CharField(choices=[('slc', 'Slc'), ('high School', 'High School'), ('bachelors', 'Bachelors'), ('master', 'Master')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
