# Generated by Django 4.0.1 on 2022-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='Hello this is a default bio provided by the developers. I love music and i love travelling. I am looking for a sweet life partner like me. Try getting conected to me if you liked my profile. See ya!', max_length=150),
            preserve_default=False,
        ),
    ]
