# Generated by Django 4.0.1 on 2022-04-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_nam_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-final_match',)},
        ),
    ]
